load("@rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")
# load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_binary(
    name = "org.example.utils",
    srcs = glob(["*.kt"]),
    deps = [],
    main_class = "MainKt",
)